demobank/demoapp/urls.py
from . import views
from django.urls import path
app_name='demoapp'
urlpatterns=[
    path('',views.homepage,name='homepage'),
    path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('form/',views.form,name='form'),
    path('applicationform/',views.applicationform,name='applicationform'),


]

demobank/demobank/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/',include('django.contrib.auth.urls')),
    path('',include('demoapp.urls'))
]
if settings.DEBUG:
     urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
     urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

demobank/demoapp/models.py
from django.db import models

# Create your models here.
from django.db import models


# Create your models here.
class formdetails(models.Model):
    Name=models.CharField(max_length=250)
    DOB = models.CharField(max_length=250)
    Age = models.CharField(max_length=250)
    Gender = models.CharField(max_length=250)
    Phone = models.CharField(max_length=250)
    Email = models.CharField(max_length=250)
    Address = models.TextField(max_length=250)
    District= models.CharField(max_length=250)
    Branch = models.CharField(max_length=250)
    Account_Type = models.CharField(max_length=250)
    Materials_Provided = models.CharField(max_length=250)
    class Meta:
        db_table='formdetails'
    def _str_(self):
        return self.Name

demobank/demoapp/forms.py
# from .models import formdetails
# from django import forms
#
#
# class Applicationform(forms.ModelForm):
#     class Meta:
#         model= formdetails
#         fields=['Name','DOB','Age','Gender','Phone','Email','Address','District','Branch','Account_Type','Materials_Provided']
#

demobank/demoapp/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from .models import formdetails

def homepage(request):
    obj = formdetails.objects.all()
    return render(request, 'homepage.html', {'result': obj})

def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        password = request.POST['password']
        cpassword = request.POST['confirmpassword']

        if password == cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request, 'Username is already taken.')
                return redirect('demoapp:register')
            elif User.objects.filter(email=email).exists():
                messages.info(request, 'Email is already taken.')
                return redirect('demoapp:register')
            else:
                user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name,
                                                password=password, email=email)
                user.save()
                print("User created")
                messages.success(request, 'Registration successful. Please log in.')
                return redirect('demoapp:login')
        else:
            messages.info(request, 'Passwords do not match.')
            return redirect('demoapp:register')

    return render(request, "register.html")

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return render(request, 'form.html')
        else:
            messages.info(request, 'Invalid credentials')
            return redirect('demoapp:login')

    return render(request, 'login.html')

def logout(request):
    auth.logout(request)
    return redirect('/')

def form(request):
    return render(request, 'form.html')

def applicationform(request):
    if request.method == 'POST':
        Name = request.POST.get('Name')
        DOB = request.POST.get('DOB')
        Age = request.POST.get('Age')
        Gender = request.POST.get('Gender')
        Phone = request.POST.get('Phone')
        Email = request.POST.get('Email')
        Address = request.POST.get('Address')
        District = request.POST.get('District')
        Branch = request.POST.get('Branch')
        Account_Type = request.POST.get('AccountType')  # Correct the field name
        Materials_provided = request.POST.get('MaterialsProvided')

        applicationform = formdetails(Name=Name, DOB=DOB, Age=Age, Gender=Gender, Phone=Phone, Email=Email,
                                      Address=Address, District=District, Branch=Branch, Account_Type=Account_Type, Materials_Provided=Materials_provided)
        applicationform.save()
        messages.info(request,"Application Submitted")

    return render(request, 'applicationform.html')

# def applicationform(request):
#     form = Applicationform(request.POST or None)
#     if form.is_valid():
#         form.save()
#
#     context = {'form': form}
#
#     return render(request, 'applicationform.html', context)

demobank/templates/applicationform.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
<!--    <script type="text/javascript">-->
<!--		var districts = {-->
<!--			"Ernakulam": ["Aluva", "Edapally"],-->
<!--			"Kozhikode": ["Koyilandy", "Vatakara"],-->
<!--			"Thiruvananthapuram": ["Neyyattinkara", "Attingal"]-->
<!--		};-->

<!--		function updateBranches() {-->
<!--			var districtSelect = document.getElementById("district");-->
<!--			var branchSelect = document.getElementById("branch");-->
<!--			var selectedDistrict = districtSelect.value;-->
<!--			branchSelect.innerHTML = "";-->

<!--			if (selectedDistrict in districts) {-->
<!--				var branches = districts[selectedDistrict];-->
<!--				for (var i = 0; i < branches.length; i++) {-->
<!--					var branch = branches[i];-->
<!--					var option = document.createElement("option");-->
<!--					option.text = branch;-->
<!--					branchSelect.add(option);-->
<!--				}-->
<!--			}-->
<!--		}-->
<!--	</script>-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body, html {
  height: 100%;
  font-family: Arial, Helvetica, sans-serif;
}

* {
  box-sizing: border-box;
}

</style>
</head>
<body>
<center>
    {{ n }}
    <form method="post" action="{% url 'demoapp:applicationform' %}" id="applicationform" role="form" novalidate="novalidate" class="bv-form">
        {% csrf_token %}

        <h2>Form</h2>
        <table>
            <tr>
                <td>Name</td>
                <td><input type="text" name="Name" required placeholder="Username" class="form-control"></td>
            </tr>
            <tr>
                <td>DOB</td>
                <td><input type="date" name="DOB" required placeholder="Date of Birth" class="form-control"></td>
            </tr>
            <tr>
                <td>Age</td>
                <td><input type="text" name="Age" required class="form-control"></td>
            </tr>
            <tr>
                <td><label>Gender:</label></td>
                <td>
                    <input type="radio" name="Gender" value="male" required> Male
                    <input type="radio" name="Gender" value="female" required> Female
                    <input type="radio" name="Gender" value="other" required> Other
                </td>
            </tr>
            <tr>
                <td>Phone</td>
                <td><input type="tel" name="Phone" minlength="10" maxlength="10" pattern="[0-9]{10}" required placeholder="Phone No" class="form-control"></td>
            </tr>
            <tr>
                <td>Email</td>
                <td><input type="email" name="Email" required class="form-control" placeholder="E-mail"></td>
            </tr>
            <tr>
                <td>Address</td>
                <td><textarea name="Address" required class="form-control"></textarea></td>
            </tr>
<!--            <tr>-->
<!--                <td><label for="district">District</label></td>-->
<!--                <td>-->
<!--                    <select id="district" name="district" onchange="updateBranches()">-->
<!--                        <option value="">&#45;&#45; Select District &#45;&#45;</option>-->
<!--			            <option value="Ernakulam">Ernakulam</option>-->
<!--			            <option value="Kozhikode">Kozhikode</option>-->
<!--			            <option value="Thiruvananthapuram">Thiruvananthapuram</option>-->
<!--		            </select>-->
<!--                </td>-->
<!--            </tr>-->
<!--            <tr>-->
<!--                <td><label for="branch">Branch:</label></td>-->
<!--                <td><select id="branch" name="branch">-->
<!--			              <option value="">&#45;&#45; Select Branch &#45;&#45;</option>-->
<!--		            </select></td>-->
<!--            </tr>-->


            <tr>
                <td>District</td>
                <td>
                    <select name="District">
                        <option value="Wayanad">Wayanad</option>
                        <option value="Kannoor">Kannoor</option>
                        <option value="Calicut">Calicut</option>
                        <option value="Malappuram">Malappuram</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td><label for="branch">Branch:</label></td>
                <td>
                    <select id="branch" name="Branch">
                        <option value="aluva">Kalpetta</option>
                        <option value="edapally">Edapally</option>
                        <option value="kakkanad">Kakkanad</option>
                    </select>
                </td>
            </tr>

            <tr>
                <td><label for="account">Account Type:</label></td>
                <td>
                    <select id="account" name="AccountType">
                        <option value="savings">Savings Account</option>
                        <option value="current">Current Account</option>
                        <option value="fixed">Fixed Deposit Account</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td><label>Materials Provided:</label></td>
                <td>
                    <input type="checkbox" id="debit" name="MaterialsProvided" value="debit">
                    <label for="debit">Debit Card</label><br>
                    <input type="checkbox" id="credit" name="MaterialsProvided" value="credit">
                    <label for="credit">Credit Card</label><br>
                    <input type="checkbox" id="cheque" name="MaterialsProvided" value="cheque">
                    <label for="cheque">Cheque Book</label><br>
                </td>
            </tr>
            <tr>
                <td></td>
            </tr>

            <tr>
                <td></td>
                <td>
                    <button type="submit">Submit</button>
                    <button><a href="{% url 'demoapp:logout' %}">Logout</a></button>
                </td>
            </tr>
        </table>
    </form>
 {% for msg in messages %}
     <h4>{{msg}}</h4>
 {% endfor %}
    <br>
<a href="{% url 'demoapp:homepage' %}" >Return to home page</a>

</center>
</body>
</html>
{% endblock %}

demobank/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'cs/custom.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/fc51e437b8.js" crossorigin="anonymous"></script>
    <link href="{% static 'css/bootstrap.min.css' rel='stylesheet' %}">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
<!--    <link href="https://kit.fontawesome.com/1b99dd44bf.js">-->
    <title>{% block title %}{% endblock %}</title>
</head>
<body class="d-flex flex-column min-vh-100" style=" font-family: 'Roboto', sans-serif;">
  <div class="container">
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}


  </div>
</body>

demobank/templates/contactform.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Django Contact Form</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<form method="POST" class="post-form" action="#">
{% csrf_token %}
<div class="container">
<div class="form-group">
	<label for="fullname" class="control-label col-sm-2">Full Name</label>
	<div class="col-sm-10">
	<input type="text" name="fullname" value=""/>
	</div>
</div>
<div class="form-group">
	<label for="email" class="control-label col-sm-2">Email</label>
	<div class="col-sm-10">
	<input type="text" name="email" value=""/>
	</div>
</div>
<div class="form-group">
	<label for="contact" class="control-label col-sm-2">Contact</label>
	<div class="col-sm-10">
	<input type="text" name="contact" value=""/>
	</div>
</div>
<div class="form-group">
	<label for="message" class="control-label col-sm-2">Message</label>
	<div class="col-sm-10">
	<input type="text" name="message" value=""/>
	</div>
</div>
<div class="form-group">
<button type="submit" class="btn btn-default">Submit</button>
</div>
</div>
</form>
</body>
</html>

demobank/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <p>please click the button below and complete the given form.</p>
<center>
    <br><br><br><br>
<button><a href="{% url 'demoapp:applicationform' %}"> application form  </a></button>

</center>
</body>
</html>

demobank/templates/homepage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
 <br><br><br><br>
<h1><b><i>WELCOME TO ABC BANK</i></b></h1><br>
 <button> <a href="{% url 'demoapp:login' %}">Click me</a></button>
  </center>
{% endblock %}

demobank/templates/login.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body, html {
  height: 100%;
  font-family: Arial, Helvetica, sans-serif;
}

* {
  box-sizing: border-box;
}

/* Add styles to the form container */
.container {
  position: relative;

  max-width: 300px;
  padding: 16px;
  background: rgba(255, 255, 255, 0.8);
  border-radius: 8px;
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1)
}

/* Full-width input fields */
input[type=text], input[type=password] {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

/* Set a style for the submit button */
.btn {
  background-color: #04AA6D;
  color: white;
  padding: 16px 20px;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

.btn:hover {
  opacity: 1;
}
</style>
</head>
<body>
<center>
    <br><br>
    <div class="bg-img">

        <form action="" method="post" class="container">
           {% csrf_token %}
            <h1>Login</h1>
            <input type="text" name="username" placeholder="enter user name"><br>
            <input type="password" name="password" placeholder="enter password"><br>
            <button type="submit" class="btn">Login</button>
        </form>
    </div>
    <div>
        <br>
        <a href="{% url 'demoapp:register' %}">click here to register</a>
        {% for msg in messages %}
            <h4>{{msg}}</h4>
        {% endfor %}
    </div>

</center>
</body>
</html>
{% endblock %}

demobank/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        {% if user.is_authenticated %}
        <li>Hello {{user.username}}</li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'demoapp:logout'%}">Logout</a>
        </li>

        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'demoapp:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'demoapp:login' %}">Login</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Branches
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Wayanad_district">wayanad</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kozhikode">calicut</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kannur">kannur</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Malappuram">Malappuram</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Idukki">Idukki</a></li>
          </ul>
        </li>
        {% endif %}

      </ul>
    </div>
  </div>
</nav>

demobank/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body, html {
  height: 100%;
  font-family: Arial, Helvetica, sans-serif;
}

* {
  box-sizing: border-box;
}

</style>
</head>
<body>
<center><h2>Registration Form</h2>
<div class="container">
    <div class="row">
        <form method="post" action="{% url 'demoapp:register' %}">
            {% csrf_token %}

            <input type="text" name="username" placeholder="enter user name"><br><br>
            <input type="text" name="first_name" placeholder="enter your first name"><br><br>
            <input type="text" name="last_name" placeholder="enter your last name"><br><br>
            <input type="email" name="email" placeholder="enter your email"><br><br>
            <input type="password" name="password" placeholder="enter password"><br><br>
            <input type="password" name="confirmpassword" placeholder="enter confirm password"><br><br>

            <button type="submit">Register</button>
        </form>
    </div>
</div>
 {% for msg in messages %}
     <h4>{{msg}}</h4>
 {% endfor %}
</center>
</body>
</html>
{% endblock %}